### ISSUE TITLE
关于损失函数问题

### ISSUE THREAD

**Issue by QingChengLineOne** [ernie-research/Tool-Augmented-Reward-Model#2]
我在reward_model.py文件中找到了rm_loss的计算方法，但是我没有找打公式2的loss的计算代码，你能指出代码所在的位置吗？

**Comment by flow3rdown** [comment]
你好，具体loss计算过程位于[此处](https://github.com/ernie-research/Tool-Augmented-Reward-Model/blob/c3f88d2a33d34bbd0b39f502a39de881994cf2e3/src/models/reward_model.py#L220-L250)，有关L_Tool, L_Observation和L_Rationale是否会加入loss的计算是通过数据处理部分实现的，参考[此处](https://github.com/ernie-research/Tool-Augmented-Reward-Model/blob/c3f88d2a33d34bbd0b39f502a39de881994cf2e3/main.py#L163)。

**Comment by QingChengLineOne** [comment]
> 你好，具体loss计算过程位于[此处](https://github.com/ernie-research/Tool-Augmented-Reward-Model/blob/c3f88d2a33d34bbd0b39f502a39de881994cf2e3/src/models/reward_model.py#L220-L250)，有关L_Tool, L_Observation和L_Rationale是否会加入loss的计算是通过数据处理部分实现的，参考[此处](https://github.com/ernie-research/Tool-Augmented-Reward-Model/blob/c3f88d2a33d34bbd0b39f502a39de881994cf2e3/main.py#L163)。
抱歉，根据你的指引，我还是没看到图中公式的loss的计算方式，你能提供更详细的说明吗？
![image](https://github.com/ernie-research/Tool-Augmented-Reward-Model/assets/111961874/c0682d00-a0a6-461c-b122-62212e94619f)

**Comment by cyk1337** [comment]
For LM loss calculation, refer to [here](https://github.com/ernie-research/Tool-Augmented-Reward-Model/blob/c3f88d2a33d34bbd0b39f502a39de881994cf2e3/src/models/reward_model.py#L233-L243).
